from .annotations import SpringBootApplication
from .annotations import *
from .ai.annotations import (
    Agent,
    AiCache,
    AiRetry,
    ContentModeration,
    Embedding,
    Prompt,
    RAG,
    StructuredOutput,
    TokenUsage,
    VectorStore,
)
from .ai.annotation_runtime import ContentModerationError
from .context import *
from .web import *
from .config import *
from .utils import *
from .main import create_app, run, SpringApplication, run_cli

__version__ = "2.3.8"
__author__ = "yuconggen"
__license__ = "MIT"

# ORM迁移
from .orm.migration import MigrationManager, MigrationError

# 核心模块（优雅退出）
from .core.graceful_shutdown import GracefulShutdown, shutdown_handler

# 安全模块
from .security.secret_manager import SecretManager, is_sensitive_key, mask_secret, resolve_secret_config
from .security.replay_protection import ReplayProtection, NonceCache, create_replay_protection

# Public top-level API. Keep it aligned with the modules imported above.
__all__ = [
    'run',
    'create_app',
    'SpringApplication',
    'SpringBootApplication',
    'run_cli',
    'ConfigLoader',
    'ConfigurationError',
    'config_loader',
    'set_global_config_loader',
    'get_config',
    'get_config_value',
    'ApplicationContext',
    'BeanDefinition',
    'BeanFactory',
    'ComponentScanner',
    'BeanRegistry',
    'WebApplicationContext',
    'Result',
    'HandlerInterceptor',
    'InterceptorRegistry',
    'GlobalExceptionHandler',
    'SpringLogger',
    'BannerPrinter',
    'MigrationManager',
    'MigrationError',
    'SecretManager',
    'ReplayProtection',
    'NonceCache',
    'create_replay_protection',
    'mask_secret',
    'is_sensitive_key',
    'resolve_secret_config',
    'GracefulShutdown',
    'shutdown_handler',
    '__version__',
    'ComponentScan',
    'ApplicationEvent',
    'EventListener',
    'RestController',
    'Controller',
    'RequestMapping',
    'GetMapping',
    'PostMapping',
    'PutMapping',
    'PatchMapping',
    'DeleteMapping',
    'Service',
    'Component',
    'Aspect',
    'Pointcut',
    'Before',
    'After',
    'Around',
    'AfterReturning',
    'AfterThrowing',
    'Repository',
    'Autowired',
    'Qualifier',
    'Configuration',
    'Scope',
    'Bean',
    'Value',
    'ConfigurationProperties',
    'RequestParam',
    'PathVariable',
    'RequestBody',
    'CrossOrigin',
    'ControllerAdvice',
    'ExceptionHandler',
    'Slf4j',
    'LogExecutionTime',
    'PostConstruct',
    'PreDestroy',
    'Primary',
    'Profile',
    'Lazy',
    'RequestHeader',
    'CookieValue',
    'ResponseStatus',
    'Transactional',
    'Cacheable',
    'Retryable',
    'Recover',
    'Async',
    'Scheduled',
    'AsyncResult',
    'RateLimit',
    'CircuitBreaker',
    'Idempotent',
    'AuditLog',
    'FeatureToggle',
    'Lock',
    'Metrics',
    'Synchronized',
    'Validate',
    'Trace',
    'PreAuthorize',
    'PostAuthorize',
    'Secured',
    'Authenticate',
    'Data',
    'Get',
    'Set',
    'ToString',
    'Prompt',
    'RAG',
    'StructuredOutput',
    'Agent',
    'Embedding',
    'VectorStore',
    'AiRetry',
    'AiCache',
    'TokenUsage',
    'ContentModeration',
    'ContentModerationError',
    'EnableDiscoveryClient',
    'NacosValue',
    'RefreshScope',
    'EnableFeignClients',
    'FeignClient',
    'SentinelResource',
    'EnableGateway',
    'LoadBalanced',
    'GlobalTransactional',
    'Valid',
    'Validated',
    'CachePut',
    'CacheEvict',
    'CacheConfig',
    'Caching',
    'Conditional',
    'ConditionalOnProperty',
    'ConditionalOnBean',
    'ConditionalOnMissingBean',
    'ConditionalOnClass',
    'RabbitListener',
    'RabbitTemplate',
    'KafkaListener',
    'KafkaTemplate',
    'kafka_template',
    'MCPCall',
    'MCPClient',
    'MCPPrompt',
    'MCPResource',
    'MCPServer',
    'MCPTool',
    'LangChainCall',
    'LangChainClient',
    'GraphEdge',
    'GraphInvoke',
    'GraphNode',
    'GraphRoute',
    'LangGraph',
    'EnableOAuth2',
    'EnableCsrf',
    'EnableDevTools',
    'EnableConfigServer',
    'EnableBus',
    'EnableBatchProcessing',
    'EnableDataRest',
    'BatchJob',
    'BatchStep',
    'RepositoryRestResource',
    'RedisClient',
    'BeanUtils',
]
